---
- name: Limpiando linux
  hosts: host.domain.ip
  become: true

  tasks:

  - name: Registing shell command (users for remove) like variable
    shell: 'awk -F: '($3 >= 1001) {printf "%s\n",$1}' /etc/passwd | sed '/nobody/d''
    register: remove_users_output

  - name: Remove Users
    user:
      name: "{{ item }}"
      state: absent
      with_items: "{{ remove_users_output }}"

  - name: Ensure user ricardo exists
    user:
    name: asix
    group: users
    groups: sudo
    uid: 1001
    password: "{{ 'lacontraseñasecreta' | password_hash('sha512') }}"
    state: present

  - name: Purge the user home
    command: "rm -rf /home/asix/"
    notify:
    - Run mkhomedir

  handlers:
    - name: Run mkhomedir
      command: "mkhomedir_helper asix"
